### ISSUE TITLE
Contact Us Form UI

### ISSUE THREAD

**Issue by wkhademi** [CSC307Fall2018/Team-Send-It#18]
Create the Contact Us Form in the Contacts Page (Related to Requirements #2 and #7)

Should Contain:
- Name space
- Phone Number space (Optional)
- Email Address space
- Message space
- Submit button

**Comment by haydenbaker** [comment]
https://scotch.io/tutorials/how-to-build-a-simple-single-page-application-using-vue-2-part-1#toc-setting-up-our-routes
